defaults: &defaults
  host: ""
  adapter: sqlite3
  user: ""
  password: ""
  migration_files_path: db/migrations # this is the default location for all migrations

development:
  db: d_development
  <<: *defaults

test:
  db: _test
  <<: *defaults

production:
  db: _production
  <<: *defaults
