# TODO
# defaults : &defaults
#   host: localhost
#   adapter: postgres
#   user: root
#   password: somepassword
#   migration_files_path: db/migrations # this is the default location for all migrations

# development:
#   db: _development
#   <<: *defaults

# test:
#   db: _test
#   <<: *defaults

# production:
#   db: _production
#   <<: *defaults
