# This file is autogenerated.
# It is used for Jennifer database operations.
# Please do not modify.

require "./config/jennifer"
require "./db/migrations/*"
require "sam"
require "jennifer/sam"
load_dependencies "jennifer"
Sam.help